[package]
name = "bitcoin_r1cs"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-381 = "0.3.0"
ark-crypto-primitives = { version = "0.3.0", features = ["r1cs"] }
ark-ec = "0.3.0"
ark-ff = { version = "0.3.0", features = ["std"] }
ark-groth16 = {version = "0.3.0", features = ["r1cs"]}
ark-r1cs-std = "0.3.0"
ark-relations = "0.3.0"
ark-serialize = "0.3.0"
byteorder = "1.5.0"
chain_gang = { git = "https://github.com/nchain-innovation/chain-gang.git", tag = "v0.6.15", package = "chain-gang" }
hex = "0.4.3"
rand = "0.8.5"
rand_chacha = "0.3.1"

ark-pcd = { git = "https://github.com/BarbacoviF/pcd.git", branch = "barbacovif/use-short-weierstrass-curve", version = "0.1.0" }
ark-mnt4-753 = {version = "0.3.0", features = ["r1cs"]}
ark-mnt6-753 = {version = "0.3.0", features = ["r1cs"]}
ark-std = "0.3.0"
sha2 = "0.10.8"
ark-bls12-377 = "0.3.0"
